#!/usr/bin/env node
// Fan the Claude-native rules out to every other agent, preserving conditional
// (glob-scoped) loading wherever the target supports it.
//
// SOURCE OF TRUTH (never written here):
//   .claude/CLAUDE.md    — always-on master rules
//   .claude/rules/*.md   — conditional rules, `globs:` frontmatter
//
// GENERATED:
//   .cursor/rules/*.mdc  — conditional preserved (globs + alwaysApply:false); master = alwaysApply:true
//   AGENTS.md            — flat: master + every rule (Codex/Gemini and any AGENTS.md reader)
//   GEMINI.md            — mirror of AGENTS.md
//
// Replaces the old `cp CLAUDE.md AGENTS.md` sync: other agents now get the full
// rule set, and Cursor gets it conditionally instead of always-on.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const MARK =
  "<!-- @generated by scripts/sync-rules.mjs from .claude/ — edit the source, not this file -->";

const stripQuotes = (s) => s.replaceAll(/^["']|["']$/g, "");

const parseFrontmatter = (md) => {
  const m = md.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) {
    return { body: md.trim(), fm: {} };
  }
  const fm = {};
  let key = null;
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^(\w[\w-]*):\s*(.*)$/);
    const item = line.match(/^\s*-\s*(.*)$/);
    if (kv) {
      const [, k, rawVal] = kv;
      const val = rawVal.trim();
      key = k;
      fm[key] = val === "" ? [] : stripQuotes(val);
    } else if (item && Array.isArray(fm[key])) {
      fm[key].push(stripQuotes(item[1].trim()));
    }
  }
  return { body: m[2].trim(), fm };
};

const asList = (v) => {
  if (Array.isArray(v)) {
    return v;
  }
  return v ? [v] : [];
};

const rulesDir = join(root, ".claude/rules");

const readRule = (file) => {
  const { fm, body } = parseFrontmatter(
    readFileSync(join(rulesDir, file), "utf-8")
  );
  return {
    body,
    description: fm.description ?? "",
    globs: asList(fm.globs),
    name: file.replace(/\.md$/, ""),
  };
};

// --- read source ---
const masterRaw = readFileSync(join(root, ".claude/CLAUDE.md"), "utf-8");
// drop the leading source-of-truth comment block from the master
const master = masterRaw.replace(/^(<!--[\s\S]*?-->\s*)+/, "").trim();
const rules = existsSync(rulesDir)
  ? readdirSync(rulesDir)
      .filter((name) => name.endsWith(".md"))
      .toSorted()
      .map(readRule)
  : [];

// --- emit .cursor/rules/*.mdc (conditional preserved) ---
const cursorDir = join(root, ".cursor/rules");
mkdirSync(cursorDir, { recursive: true });
// remove only files we previously generated, leaving hand-authored .mdc alone
for (const entry of readdirSync(cursorDir).filter((name) =>
  name.endsWith(".mdc")
)) {
  const p = join(cursorDir, entry);
  if (readFileSync(p, "utf-8").includes(MARK)) {
    rmSync(p);
  }
}

const mdc = (fmLines, body) =>
  `---\n${fmLines.join("\n")}\n---\n${MARK}\n\n${body}\n`;

writeFileSync(
  join(cursorDir, "code-standards.mdc"),
  mdc(
    [
      "description: Core code standards, tooling, git hooks, architecture",
      "alwaysApply: true",
    ],
    master
  )
);
for (const r of rules) {
  const fmLines = [
    `description: ${r.description}`,
    `globs: ${r.globs.join(",")}`,
    "alwaysApply: false",
  ];
  writeFileSync(join(cursorDir, `${r.name}.mdc`), mdc(fmLines, r.body));
}

// --- emit flat AGENTS.md + GEMINI.md (for agents with no conditional mechanism) ---
const section = (r) => {
  const scope = r.globs.length ? r.globs.join("`, `") : "**";
  return `## ${r.name}\n\n_Applies to: \`${scope}\`_\n\n${r.body}`;
};
const flat = `${[MARK, "", master, ...rules.map(section)].join("\n\n").trim()}\n`;
writeFileSync(join(root, "AGENTS.md"), flat);
writeFileSync(join(root, "GEMINI.md"), flat);

console.log(
  `[sync-rules] wrote ${rules.length + 1} .cursor/rules/*.mdc, AGENTS.md, GEMINI.md`
);
